# Generated by Django 5.2.3 on 2025-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
