# Generated by Django 5.2.3 on 2025-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_transaction_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frauddata',
            options={},
        ),
        migrations.RemoveField(
            model_name='fraudaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='frauddata',
            name='date_reported',
        ),
        migrations.RemoveField(
            model_name='frauddata',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='remark',
        ),
        migrations.AlterField(
            model_name='frauddata',
            name='fraud_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='frauddata',
            name='fraud_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='frauddata',
            table=None,
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
