# Generated by Django 5.2 on 2025-04-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
